name: RDP-NGROK-ULTIMATE

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest
    steps:
    - name: Configure Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1

    - name: Set Password
      run: |
        $Password = ConvertTo-SecureString "${{ secrets.RDP_PASSWORD }}" -AsPlainText -Force
        Set-LocalUser -Name "runneradmin" -Password $Password

    - name: Install Ngrok via Choco
      run: |
        choco install ngrok -y

    - name: Auth and Start Ngrok
      run: |
        ngrok config add-authtoken "${{ secrets.NGROK_AUTH_TOKEN }}"
        Start-Process ngrok -ArgumentList "tcp 3389"
        Start-Sleep -Seconds 30

    - name: Get Address
      run: |
        $query = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels
        $url = $query.tunnels[0].public_url
        $clean = $url.Replace("tcp://", "")
        Write-Host "------------------------------------"
        Write-Host "RDP ADDRESS: $clean"
        Write-Host "USERNAME: runneradmin"
        Write-Host "------------------------------------"

    - name: Keep Online
      run: Start-Sleep -Seconds 21600
